# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                 CachyOS Hyprland Configuration              ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

$mainMod = SUPER

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                         Source Files                        ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
source = ~/.config/hypr/config/animations.conf
source = ~/.config/hypr/config/autostart.conf
source = ~/.config/hypr/config/decorations.conf
source = ~/.config/hypr/config/environment.conf
source = ~/.config/hypr/config/input.conf
source = ~/.config/hypr/config/keybinds.conf
source = ~/.config/hypr/config/monitor.conf
source = ~/.config/hypr/config/variables.conf
source = ~/.config/hypr/config/windowrules.conf

# Modifying these configs can be done by creating a user defined config in the home directory, e.g.
## ~/.config/hypr/config/user-config.conf
# source = ~/.config/hypr/config/user-config.conf

exec-once = vicinae server
bind = $mainMod, Space, exec, vicinae toggle
layerrule = blur,vicinae
layerrule = ignorealpha 0, vicinae
layerrule = noanim, vicinae

workspace = 1, monitor:DP-1
workspace = 2, monitor:HDMI-A-1
workspace = 3, monitor:DP-2

workspace = 4, monitor:DP-1
workspace = 5, monitor:HDMI-A-1
workspace = 6, monitor:DP-2

workspace = 7, monitor:DP-1
workspace = 8, monitor:HDMI-A-1
workspace = 9, monitor:DP-2

workspace = 10, monitor:DP-1
workspace = 11, monitor:HDMI-A-1
workspace = 12, monitor:DP-2

bind = $mainMod, 1, exec, \
hyprctl dispatch workspace 1; \
hyprctl dispatch workspace 2; \
hyprctl dispatch workspace 3

bind = $mainMod, 2, exec, \
hyprctl dispatch workspace 4; \
hyprctl dispatch workspace 5; \
hyprctl dispatch workspace 6

bind = $mainMod, 3, exec, \
hyprctl dispatch workspace 7; \
hyprctl dispatch workspace 8; \
hyprctl dispatch workspace 9

bind = $mainMod, 4, exec, \
hyprctl dispatch workspace 10; \
hyprctl dispatch workspace 11; \
hyprctl dispatch workspace 12
