# Preload wallpapers (so they’re loaded into memory)
preload = ~/Pictures/wallpapers/4.jpg

# Set wallpaper per monitor
# Use `hyprctl monitors` to find monitor names
wallpaper = ,~/Pictures/wallpapers/4.jpg   # default for all

# Options
ipc = on           # allow control via hyprctl / external scripts
splash = false     # disable splash
