[Settings]
# Theme
gtk-theme-name=cachyos-nord
gtk-application-prefer-dark-theme=true

# Cursor
gtk-cursor-theme-name=capitaine-cursors
gtk-cursor-theme-size=24

# Font
gtk-font-name=JetBrainsMono Nerd Font Mono,  10
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle=hintfull
gtk-xft-rgba=rgb
gtk-xft-dpi=98304

# UI behavior
gtk-enable-animations=true
gtk-primary-button-warps-slider=false
gtk-button-images=true
gtk-menu-images=true
gtk-modules=colorreload-gtk-module:appmenu-gtk-module

# Dialogs
gtk-dialogs-use-header=true

# Scrollbars
gtk-overlay-scrolling=true

# Sound
gtk-enable-event-sounds=false
gtk-enable-input-feedback-sounds=false

# Recent files
gtk-recent-files-enabled=true
gtk-recent-files-max-age=30

# Toolbar style
gtk-toolbar-style=3
gtk-toolbar-icon-size=large-toolbar

# Tooltips
gtk-enable-tooltips=true
gtk-tooltip-timeout=500
gtk-tooltip-browse-timeout=0
gtk-tooltip-browse-mode-timeout=500

# Accessibility
gtk-keynav-use-caret=false
gtk-shell-shows-app-menu=false
gtk-shell-shows-menubar=false
gtk-shell-shows-desktop=true
gtk-decoration-layout=:minimize,maximize,close

# Double-click time
gtk-double-click-time=400
gtk-double-click-distance=5
