# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Autostart Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

source = ~/.config/hypr/config/defaults.conf

# Autostart wiki https://wiki.hyprland.org/Configuring/Keywords/#executing

# Set dark mode preference for GTK4 and QT6 applications
exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps
env = QT_QPA_PLATFORMTHEME,qt6ct

# Custom start up commands
exec-once = vicinae server
exec-once = $idlehandler
exec-once = $wallpapers

# Default start up commands
exec-once = waybar
exec-once = fcitx5 -d
exec-once = mako
exec-once = nm-applet --indicator
exec-once = solaar --window=hide
exec-once = bash -c "mkfifo /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob && tail -f /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob | wob & disown"
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# Slow app launch fix
exec-once = systemctl --user import-environment
exec-once = hash dbus-update-activation-environment 2>/dev/null
exec-once = dbus-update-activation-environment --systemd
