# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Decorations Configuration                ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

source = ~/.config/hypr/config/colors.conf

# https://wiki.hyprland.org/Configuring/Variables/#decoration

decoration {
    active_opacity = 1
    inactive_opacity = 0.98
    rounding = 8

    # https://wiki.hyprland.org/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 3
        passes = 2
        new_optimizations = true
        xray = true
        ignore_opacity = true
        noise = 0.0117
        contrast = 1.0
        brightness = 1.0
        vibrancy = 0.2
        vibrancy_darkness = 0.0
        popups = true
        popups_ignorealpha = 0.2
    }

    # https://wiki.hyprland.org/Configuring/Variables/#shadow
    shadow {
        enabled = true
        range = 20
        render_power = 3
        color = rgba(00000099)
        color_inactive = rgba(00000066)
        offset = 0 2
        scale = 1.0
    }
    
    # Dimming
    dim_inactive = false
    dim_strength = 0.05
}
