# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Enviroment Configuration                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# default variables
envd = HYPRCURSOR_SIZE,24
envd = XCURSOR_SIZE,24
envd = QT_CURSOR_SIZE,24

# AMD gaming variables
envd = PROTON_FSR4_UPGRADE,1
envd = PROTON_FSR4_RDNA3_UPGRADE,1
envd = PROTON_XESS_UPGRADE,1

# Gaming Display variables
envd = PROTON_ENABLE_WAYLAND,1
envd = PROTON_NO_WM_DECORATION,1
envd = PROTON_ENABLE_HDR,1

# Gaming Performance variables
envd = ENABLE_LAYER_MESA_ANTI_LAG,1
