# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Input Configuration                    ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Input wiki https://wiki.hyprland.org/Configuring/Variables/#input

input {
    follow_mouse = 2 # 0|1|2|3
    float_switch_override_focus = 2

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0
    force_no_accel = 1
    numlock_by_default = true
}

# See https://wiki.hyprland.org/Configuring/Keywords/#executing

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Mouse Configuration                    ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
device {
    name = logitech-usb-receiver-mouse
    sensitivity = 0.5
}

# See https://wiki.hyprland.org/Configuring/Variables/
