# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Monitor Configuration                   ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Monitor wiki https://wiki.hyprland.org/Configuring/Monitors/
monitor = DP-1, 6144x2560@120, 0x0, 1
monitor = DP-6, 2048x2560@120, 0x0, 1
monitor = DP-7, 4096x2560@60, auto-right, 1
monitor = , preferred, auto, 1

# Electron based apps use X11 as default, auto should detect wayland
env = ELECTRON_OZONE_PLATFORM_HINT, auto

misc {
	vrr = 1 # Variable refresh rate
	vfr = true # Variable frame rate
}
